---
- name: Check if k3s.service exists
  ansible.builtin.stat:
    path: /etc/systemd/system/k3s.service
  register: service_file

- name: Download K3s install script
  when: airgap_dir is undefined and not service_file.stat.exists
  ansible.builtin.get_url:
    url: https://get.k3s.io/
    timeout: 120
    dest: /usr/local/bin/k3s-install.sh
    owner: root
    group: root
    mode: 0755

- name: Download K3s binary
  when: airgap_dir is undefined and not service_file.stat.exists
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s-install.sh
  environment:
    INSTALL_K3S_SKIP_START: "true"
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
  changed_when: true

- name: Setup optional config file
  when: agent_config_yaml is defined and inventory_hostname in groups['agent']
  block:
    - name: Make config directory
      ansible.builtin.file:
        path: "/etc/rancher/k3s"
        mode: 0750
        state: directory
    - name: Copy config values
      ansible.builtin.copy:
        content: "{{ agent_config_yaml }}"
        dest: "/etc/rancher/k3s/config.yaml"
        mode: 0640

- name: Install Longhorn requirements
  community.general.zypper:
    name: 
      - open-iscsi
      - nfs-client
    state: present
    disable_recommends: false
  register: longhorn_requirements
  tags:
    - package_install
    - restore
    - agent-recover
  when: ansible_facts['distribution'] == "openSUSE Leap" or ansible_facts['distribution'] == "SLES"

- name: Install Longhorn requirements
  ansible.builtin.apt:
    name: 
      - open-iscsi
      - nfs-client
    state: present
    install_recommends: true
  register: longhorn_requirements
  tags:
    - package_install
    - restore
    - agent-recover
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Enable and start iscsid
  ansible.builtin.systemd:
    name: iscsid
    daemon_reload: true
    state: restarted
    enabled: true
  when: longhorn_requirements is changed
  tags:
    - restore
    - agent-recover

- name: Copy K3s service file
  ansible.builtin.template:
    src: "k3s.service.j2"
    dest: "/etc/systemd/system/k3s.service"
    owner: root
    group: root
    mode: "0755"
  register: k3s_service
  tags:
    - cluster_update
    - update_k3s
    - restore
    - agent-recover

- name: Enable and check K3s service
  ansible.builtin.systemd:
    name: k3s
    daemon_reload: true
    state: restarted
    enabled: true
  when: k3s_service is changed
  tags:
    - cluster_update
    - update_k3s
    - restore
    - private_registry
    - agent-recover
