---
- name: Install open-iscsi on Suse
  community.general.zypper:
    name: open-iscsi
    state: present
    disable_recommends: false
  tags:
    - package_install
    - restore
    - agent-recover
  when: ansible_facts['distribution'] == "openSUSE Leap" or ansible_facts['distribution'] == "SLES"

- name: Install nfs-client on Suse
  community.general.zypper:
    name: nfs-client
    state: present
    disable_recommends: false
  tags:
    - package_install
    - restore
    - agent-recover
  when: ansible_facts['distribution'] == "openSUSE Leap" or ansible_facts['distribution'] == "SLES"

- name: Install open-iscsi on Ubuntu
  ansible.builtin.apt:
    name: open-iscsi
    state: present
    install_recommends: true
  tags:
    - package_install
    - restore
    - agent-recover
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Install nfs-client on Ubuntu
  ansible.builtin.apt:
    name: nfs-client
    state: present
    install_recommends: true
  tags:
    - package_install
    - restore
    - agent-recover
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Enable and start iscsid
  ansible.builtin.systemd:
    name: iscsid
    daemon_reload: true
    state: restarted
    enabled: true
  tags:
    - restore
    - agent-recover

- name: Copy K3s service file
  ansible.builtin.template:
    src: "k3s.service.j2"
    dest: "/etc/systemd/system/k3s-worker.service"
    owner: root
    group: root
    mode: "0755"
  tags:
    - cluster_update
    - update_k3s
    - restore
    - agent-recover

- name: Enable and check K3s service
  ansible.builtin.systemd:
    name: k3s-worker
    daemon_reload: true
    state: restarted
    enabled: true
  tags:
    - cluster_update
    - update_k3s
    - restore
    - private_registry
    - agent-recover
