---
- name: Setup optional config file [agent]
  when: agent_config_yaml is defined and inventory_hostname in groups['agent']
  block:
    - name: Make config directory
      ansible.builtin.file:
        path: "/etc/rancher/k3s"
        mode: 0750
        state: directory
    - name: Copy config values
      ansible.builtin.copy:
        content: "{{ agent_config_yaml }}"
        dest: "/etc/rancher/k3s/config.yaml"
        mode: 0640

- name: Install Longhorn requirements
  community.general.zypper:
    name: 
      - open-iscsi
      - nfs-client
    state: present
    disable_recommends: false
  tags:
    - package_install
    - restore
    - agent-recover
  when: ansible_facts['distribution'] == "openSUSE Leap" or ansible_facts['distribution'] == "SLES"

- name: Install Longhorn requirements
  ansible.builtin.apt:
    name: 
      - open-iscsi
      - nfs-client
    state: present
    install_recommends: true
  tags:
    - package_install
    - restore
    - agent-recover
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Enable and start iscsid
  ansible.builtin.systemd:
    name: iscsid
    daemon_reload: true
    state: restarted
    enabled: true
  tags:
    - restore
    - agent-recover

- name: Copy K3s service file
  ansible.builtin.template:
    src: "k3s.service.j2"
    dest: "/etc/systemd/system/k3s.service"
    owner: root
    group: root
    mode: "0755"
  tags:
    - cluster_update
    - update_k3s
    - restore
    - agent-recover

- name: Enable and check K3s service
  ansible.builtin.systemd:
    name: k3s
    daemon_reload: true
    state: restarted
    enabled: true
  tags:
    - cluster_update
    - update_k3s
    - restore
    - private_registry
    - agent-recover
