- name: Create manifests directory on first master
  file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    owner: root
    group: root
    mode: 0644
  when: ansible_host == hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0])

- name: Copy vip to first master
  template:
    src: "vip.yaml.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/vip.yaml"
    owner: root
    group: root
    mode: 0644
  when: ansible_host == hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0])
  tags:
    - manifests

- name: Copy metallb manifest to first master
  template:
    src: "metallb.yaml.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/metallb.yaml"
    owner: root
    group: root
    mode: 0644
  when: ansible_host == hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0])
  tags:
    - manifests

- name: Copy cert-manager manifest to first master
  template:
    src: "cert-manager.yaml.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/cert-manager.yaml"
    owner: root
    group: root
    mode: 0644
  when: ansible_host == hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0])
  tags:
    - manifests

- name: Copy cert-manager issuer manifest to first master
  template:
    src: "cert-manager-issuer.yaml.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/cert-manager-issuer.yaml"
    owner: root
    group: root
    mode: 0644
  when: ansible_host == hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0])
  tags:
    - manifests
    
- name: Copy longhorn manifest to first master
  template:
    src: "longhorn.yaml.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/longhorn.yaml"
    owner: root
    group: root
    mode: 0644
  when: ansible_host == hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0])
  tags:
    - manifests
#
#- name: Copy nfs-client-provisioner manifest to first master
#  template:
#    src: "nfs-client-provisioner.yaml.j2"
#    dest: "/var/lib/rancher/k3s/server/manifests/nfs-client-provisioner.yaml"
#    owner: root
#    group: root
#    mode: 0644
#  when: ansible_host == hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0])
#  tags:
#    - manifests