- name: Download etcd {{ etcd_version }}
  get_url:
    url: https://github.com/etcd-io/etcd/releases/download/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz
    dest: /tmp/etcd-{{ etcd_version }}-linux-amd64.tar.gz
    owner: root
    group: root
    mode: 0755
  when: ansible_facts.architecture == "x86_64"
