- name: Agent node setup
  hosts: all
  remote_user: adamkoro
  become: true
  tasks:
    ###############
    ## kubelet disk
    ###############
    - name: Create a filesystem for kubelet
      community.general.filesystem:
        dev: /dev/vdb
        fstype: xfs
        force: true

    - name: Get kubelet disk UUID
      ansible.builtin.command: blkid -s UUID -o value /dev/vdb
      register: uuid_kubelet
      changed_when: false

    ###############
    ## rancher disk
    ###############
    - name: Create a filesystem for rancher
      community.general.filesystem:
        dev: /dev/vdc
        fstype: xfs
        force: true

    - name: Get rancher disk UUID
      ansible.builtin.command: blkid -s UUID -o value /dev/vdc
      register: uuid_rancher
      changed_when: false

    ###############
    ## longhorn disk
    ###############
    - name: Create a filesystem for longhorn
      community.general.filesystem:
        dev: /dev/vdd
        fstype: xfs
        force: true

    - name: Get longhorn disk UUID
      ansible.builtin.command: blkid -s UUID -o value /dev/vdd
      register: uuid_longhorn
      changed_when: false

    ###############
    ## mount created disks
    ###############
    - name: Add disks to fstab
      blockinfile:
        path: /etc/fstab
        state: present
        block: |
          UUID={{ uuid_kubelet.stdout }} /var/lib/kubelet xfs defaults 0 0
          UUID={{ uuid_rancher.stdout }} /var/lib/rancher xfs defaults 0 0
          UUID={{ uuid_longhorn.stdout }} /var/lib/longhorn xfs defaults 0 0

    - name: Create directory for mounts
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0644'
      loop:
        - "/var/lib/kubelet"
        - "/var/lib/rancher"
        - "/var/lib/longhorn"

    - name: Mount disks
      ansible.builtin.command: mount -a
      changed_when: false

    - name: Remove old kernel
      community.general.zypper:
        name: kernel-default-base
        state: absent

    - name: Install packages
      community.general.zypper:
        name: "{{ item }}"
        state: present
      loop:
        - "nfs-client"
        - "kernel-default"
