- name: Download K3S binary
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: download

- name: K3S cluster init
  hosts: k3s_cluster_init
  become: true
  roles:
    - role: k3s/cluster-init

- name: Etcd node setup
  hosts: etcd
  become: true
  roles:
    - role: k3s/etcd