---
- name: Reboot
  ansible.builtin.reboot:
    reboot_timeout: 300
    msg: "Reboot initiated by Ansible for {{ inventory_hostname }}"
  async: 0
  poll: 0
  ignore_errors: true
  register: reboot
  tags:
    - reboot
