---
- name: Drop K3S table
  community.postgresql.postgresql_table:
    login_db: '{{ postgres_database }}'
    login_host: '{{ postgres_host }}'
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    port: '{{ postgres_port }}'
    ssl_mode: '{{ postgres_ssl_mode }}'
    name: public.kine
    state: absent
    cascade: yes
  when: inventory_hostname in groups['database']
  tags:
    - delete_table
