- name: Create a filesystem for kubelet disk
  filesystem:
    dev: '{{ master_kubelet_disk }}'
    fstype: '{{ filesystem_type }}'
    force: yes
  tags:
    - partitions

- name: Create a filesystem for rancher disk
  filesystem:
    dev: '{{ master_rancher_disk }}'
    fstype: '{{ filesystem_type }}'
    force: yes
  tags:
    - partitions

- name: Get kubelet disk UUID
  command: blkid -s UUID -o value {{ master_kubelet_disk }}
  register: uuid_kubelet
  tags:
    - partitions

- name: Get rancher disk UUID
  command: blkid -s UUID -o value {{ master_rancher_disk }}
  register: uuid_rancher
  tags:
    - partitions

- name: Add disks to fstab
  blockinfile:
    path: /etc/fstab
    state: present
    block: |
      UUID={{ uuid_kubelet.stdout }} {{ kubelet_mount_path }} {{ filesystem_type }} defaults 0 0
      UUID={{ uuid_rancher.stdout }} {{ rancher_mount_path }} {{ filesystem_type }} defaults 0 0
  tags:
    - partitions

- name: Create directory for mount
  file:
    path: '{{ kubelet_mount_path }}'
    state: directory
    owner: root
    group: root
    mode: 0644
  tags:
    - partitions

- name: Create directory for mount
  file:
    path: '{{ rancher_mount_path }}'
    state: directory
    owner: root
    group: root
    mode: 0644
  tags:
    - partitions

- name: Mount disks
  command: mount -a
  tags:
    - partitions