- name: Copy etcd service
  template:
    src: "etcd.service.j2"
    dest: "/etc/systemd/system/etcd.service"
    owner: root
    group: root
    mode: 0644

- name: Enable and check etcd service
  systemd:
    name: etcd
    daemon_reload: yes
    state: restarted
    enabled: yes