- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
- hosts: master
  become: yes
  roles:
    - role: prereq/master
    - role: k3s/master
- hosts: worker
  become: yes
  roles:
    - role: prereq/worker
    - role: k3s/worker
