- hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: prereq
    - role: airgap

- hosts: server
  become: true
  roles:
    - role: k3s/cluster-init

- hosts: server
  become: true
  roles:
    - role: k3s/control-plane
