---
- name: Kill k3s-init temporary service which is used for initialization
  ansible.builtin.systemd:
    name: k3s-init
    state: stopped
  failed_when: false

- name: Copy K3s service file
  register: k3s_service
  ansible.builtin.template:
    src: "k3s.service.j2"
    dest: "/etc/systemd/system/k3s.service"
    owner: root
    group: root
    mode: "0644"

- name: Enable and check K3s service
  ansible.builtin.systemd:
    name: k3s
    daemon_reload: true
    state: restarted
    enabled: true
  when: k3s_service is changed or etcd_config_file is changed or registry_config_file is changed
