- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes
  tags:
    - preparation

- name: Install open-iscsi for Longhorn
  community.general.zypper:
    name: open-iscsi
    state: present
    disable_recommends: no
  tags:
    - package_install
