---
- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes
  tags:
    - preparation

- name: Enable IPv6 forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: yes
  tags:
    - preparation

- name: Create partitions
  include_tasks: create_partitions.yml
  tags:
    - partitioning

- name: Install open-iscsi for Longhorn
  community.general.zypper:
    name: open-iscsi
    state: present
    disable_recommends: no
  when: inventory_hostname in groups['worker'] 
  tags:
    - package_install