- hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: download

- hosts: control_plane
  become: true
  roles:
    - role: k3s-cluster-init

- hosts: control_plane
  become: true
  roles:
    - role: k3s-control-plane
