---
- name: Kill k3s-init temporary service which is used for initialization
  ansible.builtin.systemd:
    name: k3s-init
    state: stopped
  failed_when: false

- name: Copy manifests to the first node
  ansible.builtin.include_tasks: manifests.yml
  when: inventory_hostname == groups['server'][0]
  tags:
    - manifests

- name: Copy K3s service file
  register: k3s_service
  ansible.builtin.template:
    src: "k3s.service.j2"
    dest: "/etc/systemd/system/k3s.service"
    owner: root
    group: root
    mode: "0644"

- name: Enable and check K3s service
  ansible.builtin.systemd:
    name: k3s
    daemon_reload: true
    state: restarted
    enabled: true
  when: k3s_service is changed

- name: Create kubectl symlink
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: Create crictl symlink
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/crictl
    state: link

- name: Install kubectl bash completion
  ansible.builtin.shell: "/usr/local/bin/kubectl completion bash > /etc/bash_completion.d/kubectl"
  changed_when: false
  when: inventory_hostname in groups['server']

- name: Install k3s bash completion
  ansible.builtin.shell: "/usr/local/bin/k3s completion bash > /etc/bash_completion.d/k3s"
  changed_when: false
  when: inventory_hostname in groups['server']

- name: Install crictl bash completion
  ansible.builtin.shell: "/usr/local/bin/crictl completion bash > /etc/bash_completion.d/crictl"
  changed_when: false
  when: inventory_hostname in groups['server']
