- name: Create a filesystem for etcd disk
  filesystem:
    dev: '{{ etcd_disk }}'
    fstype: '{{ etcd_filesystem_type }}'
    force: yes
  when:  inventory_hostname in groups['member']
  tags:
    - partitions

- name: Get etcd disk UUID
  command: blkid -s UUID -o value {{ etcd_disk }}
  register: uuid_etcd
  when:  inventory_hostname in groups['member']
  tags:
    - partitions

- name: Add disks to fstab
  blockinfile:
    path: /etc/fstab
    state: present
    block: |
      UUID={{ uuid_etcd.stdout }} {{ etcd_mount_path }} {{ etcd_filesystem_type }} defaults 0 0
  when:  inventory_hostname in groups['member']
  tags:
    - partitions

- name: Create directory for etcd mount
  file:
    path: '{{ etcd_mount_path }}'
    state: directory
    owner: root
    group: root
    mode: 0644
  tags:
    - partitions

- name: Mount disks
  command: mount -a
  tags:
    - partitions