- name: Create manifests directory on first master
  file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    owner: root
    group: root
    mode: 0640
  tags:
    - manifests

- name: Copy kube-vip to first master
  template:
    src: "kube-vip.yaml.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/vip.yaml"
    owner: root
    group: root
    mode: 0640
  tags:
    - manifests

- name: Copy kube-vip-cloud-controller  manifest to first master
  template:
    src: "kube-vip-cloud-controller.yaml.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/kube-vip-cloud-controller.yaml"
    owner: root
    group: root
    mode: 0640
  tags:
    - manifests


- name: Copy cert-manager manifest to first master
  template:
    src: "cert-manager.yaml.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/cert-manager.yaml"
    owner: root
    group: root
    mode: 0640
  tags:
    - manifests

- name: Copy cert-manager issuer manifest to first master
  template:
    src: "cert-manager-issuer.yaml.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/cert-manager-issuer.yaml"
    owner: root
    group: root
    mode: 0640
  tags:
    - manifests

- name: Copy ingress-nginx manifest to first master
  template:
    src: "ingress-nginx.yaml.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/ingress-nginx.yaml"
    owner: root
    group: root
    mode: 0640
  tags:
    - manifests

- name: Copy longhorn manifest to first master
  template:
    src: "longhorn.yaml.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/longhorn.yaml"
    owner: root
    group: root
    mode: 0640
  tags:
    - manifests

- name: Copy minio-operator manifest to first master
  template:
    src: "minio-operator.yaml.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/minio-operator.yaml"
    owner: root
    group: root
    mode: 0640
  tags:
    - manifests

- name: Copy minio-tenant-backup manifest to first master
  template:
    src: "minio-tenant-backup.yaml.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/minio-tenant-backup.yaml"
    owner: root
    group: root
    mode: 0640
  tags:
    - manifests