- name: Remove haproxy
  include_tasks: haproxy.yaml
  when: inventory_hostname in groups['loadbalancer']

- name: Remove keepalived
  include_tasks: keepalived.yaml
  when: inventory_hostname in groups['loadbalancer']