---
- name: Remove haproxy
  ansible.builtin.include_tasks: haproxy.yaml
  when: inventory_hostname in groups['loadbalancer']

- name: Remove keepalived
  ansible.builtin.include_tasks: keepalived.yaml
  when: inventory_hostname in groups['loadbalancer']
