---
- name: Download k3s binary x64
  ansible.builtin.get_url:
    url: https://fileserver.adamkoro.local/k3s/{{ k3s_version }}/k3s
    checksum: sha256:https://fileserver.adamkoro.local/k3s/{{ k3s_version }}/sha256sum-amd64.txt
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: "0755"
  when: ansible_facts.architecture == "x86_64"
  tags:
    - update_k3s
    - etcd-recover
    - restore
