- name: Kill k3s-init temporary service which is used for initialization
  systemd:
    name: k3s-init
    state: stopped
  failed_when: false

- name: Copy K3s service file
  register: k3s_service
  template:
    src: "k3s.service.j2"
    dest: "/etc/systemd/system/k3s.service"
    owner: root
    group: root
    mode: 0644

- name: Enable and check K3s service
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes
  tags: 
    - update_k3s

