- name: Prerequriements
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: prereq
    - role: airgap

- name: Setup Nginx crm proxy cluster
  hosts: loadbalancer
  gather_facts: true
  become: true
  roles:
    - role: loadbalancer

- name: Initialize k3s cluster
  hosts: k3s_cluster_init
  become: true
  roles:
    - role: k3s-cluster-init

- name: Setup etcd nodes
  hosts: etcd
  become: true
  roles:
    - role: k3s-etcd

- name: Setup control-plane nodes
  hosts: control_plane
  become: true
  roles:
    - role: k3s-control-plane

- name: Setup agent nodes
  hosts: agent
  become: true
  roles:
    - role: k3s-agent
