- name: Setup Nginx crm proxy cluster
  hosts: loadbalancer
  gather_facts: true
  become: true
  roles:
    - role: loadbalancer

- name: K3S requriements
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: prereq
    - role: airgap

- name: Initialize K3S cluster
  hosts: k3s_cluster_init
  become: true
  roles:
    - role: k3s-cluster-init

- name: Setup etcd nodes
  hosts: etcd
  become: true
  roles:
    - role: k3s-etcd

- name: Setup server nodes
  hosts: server
  become: true
  roles:
    - role: k3s-control-plane

- name: Setup agent nodes
  hosts: agent
  become: true
  roles:
    - role: k3s-agent
