- name: Prerequriements
  hosts: agent
  gather_facts: true
  become: true
  roles:
    - role: prereq
    - role: airgap

- name: Initialize k3s cluster
  hosts: k3s_cluster_init
  become: true
  roles:
    - role: k3s/cluster-init

- name: Setup etcd nodes
  hosts: etcd
  become: true
  roles:
    - role: k3s/etcd

- name: Setup control-plane nodes
  hosts: server
  become: true
  roles:
    - role: k3s/control-plane

- name: Setup agent nodes
  hosts: agent
  become: true
  roles:
    - role: k3s/agent
