---
#############
## Server init args
#############
init_args: >-
  {% if groups['server'] | length > 1 %}
    {% if ansible_hostname == hostvars[groups['server'][0]]['ansible_hostname'] %}
      --cluster-init
    {% else %}
      --server https://{{ hostvars[groups['server'][0]].flannel_node_ip }}:6443
    {% endif %}
  {% endif %}

#############
## K3S server config
#############
server_config_yaml: |
  token:
    - {{ k3s_token }}
  tls-san:
    - "{{ cluster_endpoint }}"
  node-label:
    - "node.kubernetes.io/control-plane=true"
    - "node.longhorn.io/create-default-disk=true"
  flannel-iface: "{{ flannel_iface }}"
  node-ip: "{{ flannel_node_ip }}"
  disable:
    - servicelb
    - traefik
    - local-storage
  etcd-expose-metrics: {{ etcd_metrics_enable }}
  etcd-snapshot-schedule-cron: "{{ etcd_s3_backup_schedule }}"
  etcd-s3: {{ etcd_s3_backup_enable }}
  etcd-snapshot-compress: {{ etcd_s3_backup_compress }}
  etcd-s3-endpoint: {{ etcd_s3_backup_endpoint }}
  etcd-s3-access-key: {{ etcd_s3_backup_access_key }}
  etcd-s3-secret-key: {{ etcd_s3_backup_secret_key }}
  etcd-s3-bucket: {{ etcd_s3_backup_bucket }}
  etcd-s3-region: {{ etcd_s3_region }}