---
- name: Create a new partition for Rancher
  community.general.parted:
    device: '{{ rancher_disk }}'
    number: 1
    state: present
    label: gpt
  tags:
    - partitioning

- name: Create a new partition for Longhorn
  community.general.parted:
    device: '{{ longhorn_disk }}'
    number: 1
    state: present
    label: gpt
  when: inventory_hostname in groups['storage']
  tags:
    - partitioning


- name: Create a filesystem for Rancher
  community.general.filesystem:
    dev: '{{ rancher_disk + "1" }}'
    fstype: '{{ filesystem_type }}'
    force: yes
  tags:
    - partitioning


- name: Create a filesystem for Longhorn
  community.general.filesystem:
    dev: '{{ longhorn_disk + "1" }}'
    fstype: '{{ filesystem_type }}'
    force: yes
  when: inventory_hostname in groups['storage']
  tags:
    - partitioning


- name: Get Rancher disk UUID
  command: blkid -s UUID -o value {{ rancher_disk + '1' }}
  register: uuid_rancher
  tags:
    - partitioning


- name: Get Longhorn disk UUID
  command: blkid -s UUID -o value {{ longhorn_disk + '1' }}
  register: uuid_longhorn
  when: inventory_hostname in groups['storage']
  tags:
    - partitioning


- name: Add Rancher disk to fstab
  blockinfile:
    path: /etc/fstab
    state: present
    block: |
      UUID={{ uuid_rancher.stdout }} {{ rancher_mount_path }} {{ filesystem_type }} defaults 0 0
  tags:
    - partitioning

- name: Add Longhorn disk to fstab
  blockinfile:
    path: /etc/fstab
    state: present
    block: |
      UUID={{ uuid_longhorn.stdout }} {{ longhorn_mount_path }} {{ filesystem_type }} defaults 0 0
  when: inventory_hostname in groups['storage']
  tags:
    - partitioning


- name: Create directory for Rancher mount
  file:
    path: '{{ rancher_mount_path }}'
    state: directory
    owner: root
    group: root
    mode: 0644
  tags:
    - partitioning

- name: Create directory for Longhorn mount
  file:
    path: '{{ longhorn_mount_path }}'
    state: directory
    owner: root
    group: root
    mode: 0644
  tags:
    - partitioning


- name: Mount disks
  command: mount -a
  tags:
    - partitioning
