---
- hosts: database
  gather_facts: yes
  become: yes
  roles:
    - role: database

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: prereg-prod
    - role: download

- hosts: master
  become: yes
  roles:
    - role: k3s-prod/master

- hosts: worker
  become: yes
  roles:
    - role: k3s-prod/worker

- hosts: storage
  become: yes
  roles:
    - role: k3s-prod/storage