---
# Install keepalived
- name: Include keepalived tasks
  ansible.builtin.include_tasks: keepalived.yaml

# Install haproxy
- name: Include haproxy tasks
  ansible.builtin.include_tasks: haproxy.yaml
