---
- name: Copy K3s service file
  template:
    src: "k3s.service.j2"
    dest: "/etc/systemd/system/k3s-worker.service"
    owner: root
    group: root
    mode: 0755
  tags:
    - cluster_update

- name: Enable and check K3s service
  systemd:
    name: k3s-worker
    daemon_reload: yes
    state: restarted
    enabled: yes
  tags:
    - cluster_update
