---
# If airgapped, all K3s artifacts are already on the node.
- name: Download K3s install script
  when: airgap_dir is undefined
  ansible.builtin.get_url:
    url: https://get.k3s.io/
    timeout: 120
    dest: /usr/local/bin/k3s-install.sh
    owner: root
    group: root
    mode: 0755

- name: Download K3s binary
  when: airgap_dir is undefined
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s-install.sh
  environment:
    INSTALL_K3S_SKIP_START: "true"
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
  changed_when: true

- name: Setup optional config file [etcd]
  when: etcd_config_yaml is defined and inventory_hostname in groups['etcd']
  block:
    - name: Make config directory
      ansible.builtin.file:
        path: "/etc/rancher/k3s"
        mode: 0750
        state: directory
    - name: Copy config values
      ansible.builtin.copy:
        content: "{{ etcd_config_yaml }}"
        dest: "/etc/rancher/k3s/config.yaml"
        mode: 0640

- name: Setup optional config file [server]
  when: server_config_yaml is defined and inventory_hostname in groups['server']
  block:
    - name: Make config directory
      ansible.builtin.file:
        path: "/etc/rancher/k3s"
        mode: 0750
        state: directory
    - name: Copy config values
      ansible.builtin.copy:
        content: "{{ server_config_yaml }}"
        dest: "/etc/rancher/k3s/config.yaml"
        mode: 0640

- name: Check if kubectl is installed
  ansible.builtin.command: "/usr/local/bin/k3s kubectl version --client"
  register: kubectl_check
  ignore_errors: true
  when: inventory_hostname in groups['server'][0]

- name: Check if cluster main section is up
  block:
  - name: Verify that all etcd nodes are up
    block:
    - name: Get list of etcd nodes
      ansible.builtin.command:
        cmd: /usr/local/bin/k3s kubectl get nodes -l "node-role.kubernetes.io/etcd=true" -o=jsonpath="{.items[*].metadata.name}"
      register: nodes
      changed_when: false
    - name: Set etcd_nodes variable
      ansible.builtin.set_fact:
        etcd_nodes: true
      when: nodes.rc == 0 and (nodes.stdout.split() | length) == (groups['etcd'] | length)
    when: inventory_hostname in groups['server'][0]

  - name: Verify that all etcd nodes are up
    block:
    - name: Get list of etcd nodes
      ansible.builtin.command:
        cmd: /usr/local/bin/k3s kubectl get nodes -l "node-role.kubernetes.io/control-plane=true" -o=jsonpath="{.items[*].metadata.name}"
      register: nodes
      changed_when: false
    - name: Set server_nodes variable
      ansible.builtin.set_fact:
        server_nodes: true
      when: nodes.rc == 0 and (nodes.stdout.split() | length) == (groups['server'] | length)
    when: inventory_hostname in groups['server'][0]

  - name: init_cluster variable set to false
    ansible.builtin.set_fact:
      init_cluster: false
    when: etcd_nodes is true and server_nodes is true and inventory_hostname in groups['server'][0]
  when: kubectl_check is succeeded

- name: Init cluster
  when: init_cluster is true
  block:
  - name: Stop previous runs of k3s-init
    ansible.builtin.systemd:
      name: k3s-init
      state: stopped
    failed_when: false

  - name: Reset the failed state of the k3s-init
    ansible.builtin.command:
      cmd: systemctl reset-failed k3s-init

  - name: Init cluster on etcd nodes
    ansible.builtin.command:
      cmd: "systemd-run -p RestartSec=2 \
                        -p Restart=on-failure \
                        --unit=k3s-init \
                        /usr/local/bin/k3s server {{ etcd_init_args }}"
    when: inventory_hostname in groups['etcd']

  - name: Read k3s token
    ansible.builtin.include_tasks: ./get-token.yml

  - name: "Wait for first etcd node port"
    ansible.builtin.wait_for:
      host: "{{ hostvars[groups['etcd'][0]].flannel_node_ip }}"
      port: 6443
      delay: 10
    when: inventory_hostname in groups['server']

  - name: Init cluster on control-plane nodes
    ansible.builtin.command:
      cmd: "systemd-run -p RestartSec=2 \
                        -p Restart=on-failure \
                        --unit=k3s-init \
                        /usr/local/bin/k3s server {{ server_init_args }}"
    when: inventory_hostname in groups['server']

  - name: Verify that all etcd nodes actually joined
    ansible.builtin.command:
      cmd: /usr/local/bin/k3s kubectl get nodes -l "node-role.kubernetes.io/etcd=true" -o=jsonpath="{.items[*].metadata.name}"
    register: nodes
    until: nodes.rc == 0 and (nodes.stdout.split() | length) == (groups['etcd'] | length)
    retries: "{{ retry_count | default(20) }}"
    delay: 10
    when: inventory_hostname in groups['server']
    changed_when: false

  - name: Verify that all control-plane nodes actually joined
    ansible.builtin.command:
      cmd: /usr/local/bin/k3s kubectl get nodes -l "node-role.kubernetes.io/control-plane=true" -o=jsonpath="{.items[*].metadata.name}"
    register: nodes
    until: nodes.rc == 0 and (nodes.stdout.split() | length) == (groups['server'] | length)
    retries: "{{ retry_count | default(20) }}"
    delay: 10
    when: inventory_hostname in groups['server']
    changed_when: false
