---
k3s_version: v1.23.6+k3s1
ansible_user: YOUR_ANSIBLE_USER
systemd_dir: /etc/systemd/system

# K3s_token is required  masters can talk together securely
# This token should be alpha numeric only
k3s_token: "TOKEN"
k3s_server_location: /var/lib/rancher/k3s

# If you're using Metallb like me, only one parameters is required that's --no-deploy servicelb, change others what u prefer
extra_server_args: "--no-deploy servicelb --write-kubeconfig-mode 644"

# Kubeconfig cluster name
kconfig_cluster_name: "mgmt"

# Cloudflare credentials for Let's encrypt certs
cloudflare_email: "YOUR_CLOUDFLARE_EMAIL"
cloudflare_api_key: "YOUR_CLOUDFLARE_API_KEY"

# Cert-manager setting
cert_manager_version: "v1.8.0"

# Rancher setting
rancher_version: "2.6.5"
rancher_password: ""
rancher_hostname: "rancher.YOURDOMAIN.com"
rancher_replica_number: 1

# Metallb settings
metal_lb_version: "v0.12.1"
metal_lb_ip_range: "192.168.1.6-192.168.1.10"

# Kubernetes API endpiont
apiserver_endpoint: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
