---
- name: Install open-iscsi for Longhorn
  community.general.zypper:
    name: open-iscsi
    state: present
    disable_recommends: false
  tags:
    - package_install
    - restore

- name: Install nfs-client
  community.general.zypper:
    name: nfs-client
    state: present
    disable_recommends: false
  tags:
    - package_install
    - restore

- name: Enable and start iscsid
  ansible.builtin.systemd:
    name: iscsid
    daemon_reload: true
    state: restarted
    enabled: true
  tags:
    - restore

- name: Copy K3s service file
  ansible.builtin.template:
    src: "k3s.service.j2"
    dest: "/etc/systemd/system/k3s-worker.service"
    owner: root
    group: root
    mode: "0755"
  tags:
    - cluster_update
    - update_k3s
    - restore

- name: Enable and check K3s service
  ansible.builtin.systemd:
    name: k3s-worker
    daemon_reload: true
    state: restarted
    enabled: true
  tags:
    - cluster_update
    - update_k3s
    - restore
    - private_registry
