---
- name: Unmount longhorn device
  mount:
    path: '{{ longhorn_mount_path }}'
    state: absent
  when: inventory_hostname in groups['storage']
  tags:
    - partitions
    - longhorn_disk

- name: Read longhorn device info
  community.general.parted: device='{{ longhorn_disk }}' unit=MiB
  register: longhorn_disk_info
  when: inventory_hostname in groups['storage']
  tags:
    - partitions
    - longhorn_disk

- name: Remove all partitions from longhorn
  community.general.parted:
    device: '{{ longhorn_disk }}'
    number: '{{ item.num }}'
    state: absent
  loop: '{{ longhorn_disk_info.partitions }}'
  when: inventory_hostname in groups['storage']
  tags:
    - partitions
    - longhorn_disk