---
k3s_version: v1.23.6+k3s1
ansible_user: YOUR_ANSIBLE_USER
systemd_dir: /etc/systemd/system

# K3s_token is required  masters can talk together securely
# This token should be alpha numeric only
k3s_token: "TOKEN"
k3s_server_location: /var/lib/rancher/k3s

master_node_taints: "CriticalAddonsOnly=true:NoExecute"
# This taints and labels allows Longhorn to run and schedule own pods for storage
#storage_node_taints: "StorageOnly=true:NoSchedule"
storage_node_labels: "node.longhorn.io/create-default-disk={{ longhorn_disk_on_labeled_node }}"
# If you're using Metallb like me, only one parameters is required that's --no-deploy servicelb, change others what u like
datastore_endpoint: "postgres://{{ postgres_user + ':' + postgres_password + '@' + postgres_host + ':' + postgres_port + '/' + postgres_database + '?sslmode=' + postgres_ssl_mode  }}"
extra_server_args: "--no-deploy servicelb --write-kubeconfig-mode 644"
extra_agent_args: ""

# Kubeconfig cluster name
kconfig_cluster_name: "prod"

# Cloudflare credentials for Let's encrypt certs
cloudflare_email: "YOUR_CLOUDFLARE_EMAIL"
cloudflare_api_key: "YOUR_CLOUDFLARE_API_KEY"

# Postgres connection settings
postgres_database: "k3s-db"
postgres_user: "k3s-user"
postgres_password: "k3s-password"
postgres_host: "{{ hostvars[groups['database'][0]]['postgres_host'] | default(groups['database'][0]) }}"
postgres_port: "5432"
postgres_ssl_mode: disable
postgres_connection_network: "192.168.1.0/24"

# Longhorn setting
longhorn_version: "1.2.4"
longhorn_ingress_enabled: "true"
longhorn_hostname: "longhorn.YOURDOMAIN.com"
longhorn_replica_number: 2
longhorn_disk_on_labeled_node: "true"
longhorn_backup_path: "nfs://YOUR_NFS_SHARE_IP/YOUR_NFS_STORAGE"

# Cert-manager setting
cert_manager_version: "v1.8.0"

# Kuve-VIP settings
kube_vip_tag_version: "v0.4.2"
apiserver_endpoint: "192.168.1.30"
flannel_iface: "eth0"

# Metallb settings
metal_lb_version: "v0.12.1"
metal_lb_ip_range: "192.168.1.50-192.168.1.60"

# NFS storage provisioner
nfs_storage_host: "YOUR_NFS_SHARE_IP"
nfs_storage_path: "YOUR_NFS_STORAGE"

# Host disk settings
filesystem_type: "ext4"
postgres_disk: "/dev/sdb"
postgres_mount_path: "/var/lib/pgsql"
rancher_disk: "/dev/sdb"
rancher_mount_path: "/var/lib/rancher"
longhorn_disk: "/dev/sdc"
longhorn_mount_path: "/var/lib/longhorn"